import {
  acodes,
  blue,
  freelance,
  hilti,
  huawei,
  magik,
  sunway,
  unilah,
} from '../assets/images';

export const experiences = [
  {
    title: 'Lab Assistant',
    company_name: 'Sunway iLab',
    icon: sunway,
    iconBg: '#accbe1',
    date: 'March 2019 - April 2019',
    points: [
      'Provided technical support to students for laboratory projects and assignments',
      'Guided students in the proper operation of specialized laboratory equipment',
      'Maintained and organized the laboratory environment to ensure safety and operational efficiency',
    ],
  },
  {
    title: 'Software Engineer (Internship)',
    company_name: 'Blue Ocean IT Sdn Bhd',
    icon: blue,
    iconBg: '#fbc3bc',
    date: 'May 2021 - Jul 2021',
    points: [
      'Resolved UI/UX inconsistencies across web platforms using AngularJS',
      'Developed modular frontend features tailored to diverse user requirements',
      'Architected RESTful APIs to facilitate seamless data communication between frontend and backend systems',
      'Optimized backend processing logic utilizing the Python Django framework',
      'Administered and maintained relational databases using SQL Server',
    ],
  },
  {
    title: 'Software Engineer',
    company_name: 'Magik Tech Sdn Bhd',
    icon: magik,
    iconBg: '#ffaaee',
    date: 'Jul 2021 - Dec 2021',
    points: [
      'Developed responsive web applications using the Vue.js framework',
      'Addressed cross-device compatibility issues for optimized mobile and tablet experiences',
      'Designed and implemented APIs to ensure robust data flow across system layers',
      'Refined backend business logic and server-side processing using PHP',
      'Managed the full deployment lifecycle of web systems into production environments',
    ],
  },
  {
    title: 'IT Intern',
    company_name: 'HILTI Asia IT Services Sdn Bhd',
    icon: hilti,
    iconBg: '#a2d2ff',
    date: 'Oct 2022 - Jan 2023',
    points: [
      'Conducted comprehensive API testing to ensure reliability and performance of internal services',
      'Engineered an automated testing suite using Java Spring Boot and Cucumber to streamline the development lifecycle',
      'Orchestrated CI/CD pipelines on GitLab to automate the execution and monitoring of test suites',
    ],
  },
  {
    title: 'Frontend Web Developer',
    company_name: 'Acodes Technology Sdn Bhd',
    icon: acodes,
    iconBg: '#a2efa2',
    date: 'Aug 2023 - Feb 2024',
    points: [
      'Built scalable web interfaces using React, Next.js, and Tailwind CSS',
      'Implemented efficient data fetching and synchronization using React Query',
      'Managed complex application state through Redux for enhanced performance and predictability',
      'Collaborated in the design and architectural planning of robust web solution architectures',
    ],
  },
  {
    title: 'Software Engineer',
    company_name: 'UniLah The Student App',
    icon: unilah,
    iconBg: '#088899',
    date: 'Nov 2023 - Jun 2024',
    points: [
      'Developed high-performance web pages utilizing React, TypeScript, and Tailwind CSS',
      'Engineered scalable backend services and CRUD operations using NestJS and TypeScript',
      'Enhanced cross-platform mobile application features using React Native',
      'Streamlined the integration of backend APIs with frontend architectures',
      'Executed comprehensive User Acceptance Testing (UAT) to validate UI integrity and functional requirements',
    ],
  },
  {
    title: 'Full Stack Developer',
    company_name: 'Freelance',
    icon: freelance,
    iconBg: '#ccffff',
    date: 'Mar 2022 - Now',
    points: [
      'Consulted for diverse clients across the hospitality, healthcare, and education sectors to deliver bespoke full-stack solutions.',
      'Architected and deployed scalable web applications using modern technologies, prioritizing performance and user experience.',
      'Designed and maintained robust CI/CD pipelines and highly scalable infrastructures utilizing containerization technologies.',
      'Automated critical workflows and system processes to significantly enhance operational efficiency.',
    ],
  },
  {
    title: 'Network Engineer',
    company_name: 'Huawei International Pte Ltd',
    icon: huawei,
    iconBg: '#ffddaa',
    date: 'May 2024 - Now',
    points: [
      'Engineered enterprise-grade network solutions to address complex, high-availability business requirements.',
      'Contributed to large-scale greenfield deployments and infrastructure integration projects for multinational organizations.',
      'Spearheaded complex network migration initiatives from legacy Cisco systems to modern Huawei infrastructure.',
      'Provisioned and managed enterprise wireless infrastructure, ensuring robust connectivity and security.',
      "Orchestrated Software-Defined Networking (SDN) solutions utilizing Huawei's iMaster NCE Campus and Fabric for centralized network management.",
    ],
  },
];
