import {
  acodes,
  blue,
  freelance,
  hilti,
  huawei,
  magik,
  sunway,
  unilah,
} from '../assets/images';

export const experiences = [
  {
    title: 'Lab Assistant',
    company_name: 'Sunway iLab',
    icon: sunway,
    iconBg: '#accbe1',
    date: 'March 2019 - April 2019',
    points: [
      'Help out students in their lab projects',
      'Assist students in using the different lab equipments',
      'Clean up and arrange the lab environment',
    ],
  },
  {
    title: 'Software Engineer (Internship)',
    company_name: 'Blue Ocean IT Sdn Bhd',
    icon: blue,
    iconBg: '#fbc3bc',
    date: 'May 2021 - Jul 2021',
    points: [
      'Fix UI issues on websites using Angular JS',
      'Implement new frontend features and functions based on different user requirements',
      'Create APIs for data communication between frontend and backend',
      'Modify backend server processing logic using Python Django framework',
      'Manage website database using SQL Server',
    ],
  },
  {
    title: 'Software Engineer',
    company_name: 'Magik Tech Sdn Bhd',
    icon: magik,
    iconBg: '#ffaaee',
    date: 'Jul 2021 - Dec 2021',
    points: [
      'Create web pages for systems using Vue.js',
      'Fix responsive issues on websites for mobile devices and tablets',
      'Create API for data communication between frontend and backend',
      'Modify backend server processing logic using PHP',
      'Deploy web systems to production',
    ],
  },
  {
    title: 'IT Intern',
    company_name: 'HILTI Asia IT Services Sdn Bhd',
    icon: hilti,
    iconBg: '#a2d2ff',
    date: 'Oct 2022 - Jan 2023',
    points: [
      'Perform different test operations on APIs developed by other team members',
      'Create an automated test suite for the development team using Java Spring Boot and Cucumber Framework',
      'Manage CI/CD operations on GitLab for the automated test suite',
    ],
  },
  {
    title: 'Frontend Web Developer',
    company_name: 'Acodes Technology Sdn Bhd',
    icon: acodes,
    iconBg: '#a2efa2',
    date: 'Aug 2023 - Feb 2024',
    points: [
      'Worked on creating web pages using React Next.js framework and Tailwind CSS',
      'Worked on integrating APIs using React Query',
      'Worked on handling data state management using Redux',
      'Helped in designing solution architecture for web systems',
    ],
  },
  {
    title: 'Software Engineer',
    company_name: 'UniLah The Student App',
    icon: unilah,
    iconBg: '#088899',
    date: 'Nov 2023 - Jun 2024',
    points: [
      'Worked on creating web pages using React, Typescript and Tailwind CSS',
      'Worked on handling backend CRUD and other operations using Nest.js and Typescript',
      'Worked on improving certain app functionalities using React Native',
      'Worked on integration of backend APIs onto the frontend website',
      'Helped conducted various UAT tests towards the frontend websites (for both UI and functionalities)',
    ],
  },
  {
    title: 'Full Stack Developer (Freelance)',
    company_name: 'Remote',
    icon: freelance,
    iconBg: '#ccffff',
    date: 'Mar 2022 - Now',
    points: [
      'Worked on creating web pages in React Next.js framework based on different wireframe designs',
      'Worked on creating full stack web applications using Angular.js, Express.js and MongoDB',
      'Worked on creating desktop applications using Java NetBeans',
      'Worked on creating systems using Bash',
      'Worked on creating Android applications using Android Studio and Flutter',
    ],
  },
  {
    title: 'Network Engineer',
    company_name: 'Huawei International Pte Ltd',
    icon: huawei,
    iconBg: '#ffddaa',
    date: 'May 2024 - Now',
    points: [
      'Worked on designing and implementing network solutions for enterprises',
      'Worked on network migration activities (from Cisco to Huawei) for enterprises',
      'Worked on managing firewalls to control network traffic for enterprises',
      'Worked on onboarding and managing wireless access points (AP) using wireless access controllers (AC)',
      "Worked on utilizing Huawei's iMaster NCE system (Campus & CampusInsight) in managing existing network devices",
    ],
  },
];
