import {
  css,
  express,
  git,
  github,
  html,
  javascript,
  mongodb,
  mui,
  nextjs,
  nodejs,
  react,
  tailwindcss,
  typescript,
  angular,
  vue,
  php,
  python,
  java,
  flutter,
  mysql,
  ubuntu,
  debian,
  kali,
  windows,
  gitlab,
  nestjs,
  firebase,
  expo,
  django,
  flask,
  tensorflow,
  opencv,
  numpy,
  spring,
  bootstrap,
  androidstudio,
  euleros,
  postgresql,
  supabase,
  laravel,
} from '../assets/icons';
import { huawei } from '../assets/images';

export const skills = [
  {
    imageUrl: css,
    name: 'CSS',
    type: 'Frontend',
  },
  {
    imageUrl: express,
    name: 'Express',
    type: 'Backend',
  },
  {
    imageUrl: git,
    name: 'Git',
    type: 'Version Control',
  },
  {
    imageUrl: github,
    name: 'GitHub',
    type: 'Version Control',
  },
  {
    imageUrl: gitlab,
    name: 'GitLab',
    type: 'Version Control',
  },
  {
    imageUrl: html,
    name: 'HTML',
    type: 'Frontend',
  },
  {
    imageUrl: javascript,
    name: 'JavaScript',
    type: 'Frontend',
  },
  {
    imageUrl: mongodb,
    name: 'MongoDB',
    type: 'Database',
  },
  {
    imageUrl: mui,
    name: 'Material-UI',
    type: 'Frontend',
  },
  {
    imageUrl: bootstrap,
    name: 'Bootstrap',
    type: 'Frontend',
  },
  {
    imageUrl: nextjs,
    name: 'Next.js',
    type: ['Frontend', 'Backend'],
  },
  {
    imageUrl: nestjs,
    name: 'Nest.js',
    type: 'Backend',
  },
  {
    imageUrl: firebase,
    name: 'Firebase',
    type: ['Backend', 'Database'],
  },
  {
    imageUrl: nodejs,
    name: 'Node.js',
    type: 'Backend',
  },
  {
    imageUrl: react,
    name: 'React',
    type: 'Frontend',
  },
  {
    imageUrl: tailwindcss,
    name: 'Tailwind CSS',
    type: 'Frontend',
  },
  {
    imageUrl: typescript,
    name: 'TypeScript',
    type: 'Frontend',
  },
  {
    imageUrl: angular,
    name: 'Angular',
    type: 'Frontend',
  },
  {
    imageUrl: vue,
    name: 'Vue',
    type: 'Frontend',
  },
  {
    imageUrl: php,
    name: 'PHP',
    type: 'Backend',
  },
  {
    imageUrl: python,
    name: 'Python',
    type: ['Backend', 'AI'],
  },
  {
    imageUrl: django,
    name: 'Django',
    type: 'Backend',
  },
  {
    imageUrl: flask,
    name: 'Flask',
    type: 'Backend',
  },
  {
    imageUrl: laravel,
    name: 'Laravel',
    type: 'Backend',
  },
  {
    imageUrl: java,
    name: 'Java',
    type: ['Backend', 'Application'],
  },
  {
    imageUrl: spring,
    name: 'Spring',
    type: 'Backend',
  },
  {
    imageUrl: flutter,
    name: 'Flutter',
    type: 'Application',
  },
  {
    imageUrl: expo,
    name: 'Expo',
    type: 'Application',
  },
  {
    imageUrl: react,
    name: 'React Native',
    type: 'Application',
  },
  {
    imageUrl: androidstudio,
    name: 'Android Studio',
    type: 'Application',
  },
  {
    imageUrl: mysql,
    name: 'MySQL',
    type: 'Database',
  },
  {
    imageUrl: postgresql,
    name: 'PostgreSQL',
    type: 'Database',
  },
  {
    imageUrl: supabase,
    name: 'Supabase',
    type: ['Backend', 'Database'],
  },
  {
    imageUrl: tensorflow,
    name: 'Tensorflow',
    type: 'AI',
  },
  {
    imageUrl: opencv,
    name: 'OpenCV',
    type: 'AI',
  },
  {
    imageUrl: numpy,
    name: 'Numpy',
    type: 'AI',
  },
  {
    imageUrl: debian,
    name: 'Debian Linux',
    type: 'OS',
  },
  {
    imageUrl: ubuntu,
    name: 'Ubuntu Linux',
    type: 'OS',
  },
  {
    imageUrl: kali,
    name: 'Kali Linux',
    type: 'OS',
  },
  {
    imageUrl: windows,
    name: 'Microsoft Windows',
    type: 'OS',
  },
  {
    imageUrl: euleros,
    name: 'Euler OS',
    type: 'OS',
  },
  {
    imageUrl: huawei,
    name: 'Switches (Campus & Data Center), AP, AC, Servers',
    type: 'Network',
  },
];
